### ISSUE TITLE
Wrong timezone data for french oversea territories

### ISSUE THREAD

**Issue by barbudor** [rjkip/tasmota-tz#1]
Hi Reiner

Thanks for your nice tool.
I noticed that it give wrong information for french oversea territories such as Antilles islands in the Carribean (Martinique, Guadeloupe) or La Reunion (island east of Madagascar, close to Mauritius) as they are given the same timezone as Europe/Paris

Best regards

**Comment by rjkip** [comment]
That's really unfortunate! I've mitigated the issue by listing all other time zones below the suggested ones. Maybe I'll look into where these time zones are in the database one day.

**Comment by barbudor** [comment]
thanks
